# Generated by Django 3.1.6 on 2021-04-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0002_item_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='binfo',
        ),
    ]
