# Generated by Django 3.1.6 on 2021-04-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0003_auto_20210414_0522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='binfo',
            new_name='bcode',
        ),
    ]
