# Generated by Django 3.1.6 on 2021-04-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0004_auto_20210419_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='bcode',
            new_name='binfo',
        ),
    ]
