# Generated by Django 3.1.6 on 2021-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0008_author_btitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bgenre',
            field=models.TextField(default=''),
        ),
    ]
