# Generated by Django 3.1.6 on 2021-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0009_author_bgenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='item',
            name='bauth',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='bgenre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='btitle',
            field=models.TextField(default=''),
        ),
    ]
