# Generated by Django 3.1.6 on 2021-04-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0011_auto_20210425_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.RemoveField(
            model_name='item',
            name='list',
        ),
    ]
