# Generated by Django 3.1.6 on 2021-04-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0013_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='BorrId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.borrower'),
        ),
    ]
