# Generated by Django 3.1.6 on 2021-04-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0014_item_borrid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='BorrId',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
