# Generated by Django 3.1.6 on 2021-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0018_item_mainid'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='MainID_id',
            field=models.TextField(default=''),
        ),
    ]
