# Generated by Django 3.1.6 on 2021-04-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0019_borrower_mainid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='MainID_id',
        ),
    ]
