# Generated by Django 3.1.6 on 2021-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0020_remove_borrower_mainid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.TextField(default=''),
        ),
    ]
