# Generated by Django 3.1.6 on 2021-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0021_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
