# Generated by Django 3.1.6 on 2021-04-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0023_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='Location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='borrower',
            name='Reader',
            field=models.TextField(default=''),
        ),
    ]
