# Generated by Django 3.1.6 on 2021-05-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0024_auto_20210427_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='Code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='borrower',
            name='FavAuthor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='borrower',
            name='FavBook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='borrower',
            name='Number',
            field=models.TextField(default=''),
        ),
    ]
