# Generated by Django 3.1.6 on 2021-05-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0025_auto_20210502_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='Number',
            new_name='Genre',
        ),
    ]
