# Generated by Django 3.1.6 on 2021-05-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0026_auto_20210502_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='FavAuthor',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='FavBook',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='Genre',
        ),
    ]
