# Generated by Django 3.1.6 on 2021-05-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0028_borrower_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='code',
            new_name='Number',
        ),
        migrations.AddField(
            model_name='borrower',
            name='ReadId',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='borrower',
            name='School',
            field=models.TextField(default=''),
        ),
    ]
