# Generated by Django 3.1.6 on 2021-05-11 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0031_auto_20210511_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowId', models.TextField(default='')),
                ('DateBorr', models.DateField(default='')),
                ('DueDate', models.DateField(default='')),
                ('MainID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.borrower')),
                ('binfo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.item')),
            ],
        ),
    ]
