# Generated by Django 3.1.6 on 2021-05-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0032_brtrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnId', models.TextField(default='')),
                ('DateRet', models.DateField(default='')),
                ('DueDate', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.brtrans')),
                ('MainID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.borrower')),
                ('binfo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.item')),
            ],
        ),
    ]
