# Generated by Django 3.1.6 on 2021-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0037_auto_20210521_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrtrans',
            name='DateBorr',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='DateRet',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='DueDate',
            field=models.DateTimeField(default=''),
        ),
    ]
