# Generated by Django 3.1.6 on 2021-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0038_auto_20210521_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrtrans',
            name='DateBorr',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='DateRet',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='DueDate',
            field=models.DateField(default=''),
        ),
    ]
