# Generated by Django 3.1.6 on 2021-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0039_auto_20210521_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrtrans',
            name='DateBorr',
            field=models.DateField(),
        ),
    ]
