# Generated by Django 3.1.6 on 2021-05-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0040_auto_20210521_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default='')),
                ('Mode', models.TextField(default='')),
                ('Status', models.TextField(default='')),
                ('borrId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.borrower')),
            ],
        ),
        migrations.RemoveField(
            model_name='dontrans',
            name='DateCon',
        ),
        migrations.RemoveField(
            model_name='dontrans',
            name='DateTrans',
        ),
        migrations.RemoveField(
            model_name='dontrans',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='dontrans',
            name='borrId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='IReadApp.borrower'),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='DateBorr',
            field=models.DateField(default=''),
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
