# Generated by Django 3.1.6 on 2021-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0041_auto_20210522_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrtrans',
            name='DateBorr',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='DateRet',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='DueDate',
            field=models.DateTimeField(),
        ),
    ]
