# Generated by Django 3.1.6 on 2021-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0044_auto_20210522_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='dontrans',
            name='Categories',
            field=models.TextField(default=''),
        ),
    ]
