# Generated by Django 3.1.6 on 2021-05-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0045_dontrans_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='Query',
        ),
        migrations.AddField(
            model_name='penalty',
            name='DatePaid',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrtrans',
            name='Remarks',
            field=models.TextField(default='On Process'),
        ),
        migrations.AlterField(
            model_name='dontrans',
            name='Status',
            field=models.TextField(default='Pending'),
        ),
    ]
