# Generated by Django 3.1.6 on 2021-05-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0046_auto_20210525_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrtrans',
            name='DueDate',
            field=models.TextField(default=''),
        ),
    ]
