# Generated by Django 3.1.6 on 2021-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0047_auto_20210530_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='dontrans',
            name='Channel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='penalty',
            name='Checking',
            field=models.TextField(default='On Process'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='Details',
            field=models.TextField(default=''),
        ),
    ]
