# Generated by Django 3.1.6 on 2021-06-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IReadApp', '0048_auto_20210609_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrtrans',
            name='PenEstimate',
            field=models.TextField(default=''),
        ),
    ]
